-- Schema PostgreSQL cuối cùng cho khởi tạo mới (20 bảng).
-- Mọi thay đổi cấu trúc được cập nhật trực tiếp trong file này.
-- IF NOT EXISTS chỉ cho phép khởi động lại cùng schema; không nâng cấp database cũ.

-- 1. ROLE (Vai trò)
CREATE TABLE IF NOT EXISTS role (
    role_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name            text NOT NULL UNIQUE,
    description          text,
    requires_approval    INTEGER NOT NULL DEFAULT 1 CHECK (requires_approval IN (0,1)),
    CONSTRAINT role_name_allowed CHECK (role_name IN ('USER','DOCTOR','RECEPTIONIST','NURSE','ADMIN'))
);

-- 2. USERS (Tài khoản người dùng)
CREATE TABLE IF NOT EXISTS users (
    user_id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id            INTEGER NOT NULL REFERENCES role(role_id),
    full_name          text NOT NULL CHECK (trim(full_name) <> ''),
    phone              text UNIQUE,
    email              text UNIQUE,
    password_hash      text NOT NULL CONSTRAINT users_password_hash_nonempty CHECK (trim(password_hash) <> ''),
    approval_status    text NOT NULL DEFAULT 'PENDING'
        CHECK (approval_status IN ('PENDING','APPROVED','REJECTED')),
    account_status     text NOT NULL DEFAULT 'ACTIVE'
        CHECK (account_status IN ('ACTIVE','LOCKED')),
    email_verified     INTEGER NOT NULL DEFAULT 0 CHECK (email_verified IN (0,1)),
    deleted_at         TIMESTAMPTZ,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_phone_nonempty CHECK (phone IS NULL OR trim(phone) <> ''),
    CONSTRAINT users_email_nonempty CHECK (email IS NULL OR trim(email) <> '')
);

-- 3. AUTH_TOKEN (Token xác thực)
CREATE TABLE IF NOT EXISTS auth_token (
    token_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       INTEGER NOT NULL REFERENCES users(user_id),
    token_type    text NOT NULL CHECK (token_type IN ('RESET_PASSWORD','VERIFY_EMAIL','OTP')),
    token_hash    text NOT NULL CHECK (trim(token_hash) <> ''),
    expires_at    TIMESTAMPTZ NOT NULL,
    used_at       TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT auth_token_expiry CHECK (expires_at > created_at),
    CONSTRAINT auth_token_used_time CHECK (used_at IS NULL OR used_at >= created_at)
);

-- 4. PATIENT (Hồ sơ bệnh nhân)
CREATE TABLE IF NOT EXISTS patient (
    patient_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             INTEGER REFERENCES users(user_id),
    full_name           text NOT NULL CHECK (trim(full_name) <> ''),
    dob                 DATE,
    gender              text,
    id_card             text,
    address             text,
    phone               text,
    health_insurance    text,
    archived_at         TIMESTAMPTZ,
    relationship        text CHECK (relationship IN ('SELF','PARENT','CHILD','SPOUSE','OTHER')),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 5. DEPARTMENT (Chuyên khoa)
CREATE TABLE IF NOT EXISTS department (
    department_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             text NOT NULL CHECK (trim(name) <> ''),
    description      text,
    is_active        INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 6. DOCTOR_PROFILE (Hồ sơ bác sĩ)
CREATE TABLE IF NOT EXISTS doctor_profile (
    doctor_profile_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              INTEGER NOT NULL UNIQUE REFERENCES users(user_id),
    department_id        INTEGER NOT NULL REFERENCES department(department_id),
    academic_degree      text,
    specialization       text,
    experience_years     integer NOT NULL DEFAULT 0 CHECK (experience_years >= 0),
    introduction         text,
    consultation_fee     BIGINT NOT NULL DEFAULT 0 CHECK (consultation_fee >= 0),
    avatar_url           text,
    is_active            INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 7. ROOM (Phòng khám)
CREATE TABLE IF NOT EXISTS room (
    room_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id    INTEGER NOT NULL REFERENCES department(department_id),
    room_name        text NOT NULL CHECK (trim(room_name) <> ''),
    description      text,
    is_active        INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 8. WORK_SCHEDULE (Lịch làm việc)
CREATE TABLE IF NOT EXISTS work_schedule (
    schedule_id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_profile_id     INTEGER NOT NULL REFERENCES doctor_profile(doctor_profile_id),
    room_id               INTEGER NOT NULL REFERENCES room(room_id),
    work_date             DATE NOT NULL,
    start_time            TIME NOT NULL,
    end_time              TIME NOT NULL,
    max_quota             integer NOT NULL CHECK (max_quota > 0),
    booked_count          integer NOT NULL DEFAULT 0,
    last_queue_number     INTEGER NOT NULL DEFAULT 0 CHECK (last_queue_number >= 0),
    schedule_status       text NOT NULL DEFAULT 'OPEN'
        CHECK (schedule_status IN ('OPEN','FULL','CLOSED','UNAVAILABLE')),
    unavailable_reason    text,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT schedule_time_order CHECK (end_time > start_time),
    CONSTRAINT schedule_quota CHECK (booked_count BETWEEN 0 AND max_quota),
    CONSTRAINT schedule_doctor_start_unique UNIQUE (doctor_profile_id, work_date, start_time),
    CONSTRAINT schedule_room_start_unique UNIQUE (room_id, work_date, start_time)
);

-- 9. ENCOUNTER (Lượt khám)
CREATE TABLE IF NOT EXISTS encounter (
    encounter_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    encounter_type           text NOT NULL CHECK (encounter_type IN ('ONLINE','WALK_IN')),
    patient_id           INTEGER NOT NULL REFERENCES patient(patient_id),
    doctor_profile_id    INTEGER NOT NULL REFERENCES doctor_profile(doctor_profile_id),
    schedule_id          INTEGER NOT NULL REFERENCES work_schedule(schedule_id),
    room_id              INTEGER REFERENCES room(room_id),
    created_by_id        INTEGER REFERENCES users(user_id),
    consultation_fee_snapshot BIGINT CHECK (consultation_fee_snapshot >= 0),
    deposit_amount_snapshot   BIGINT CHECK (deposit_amount_snapshot >= 0),
    symptoms             text,
    encounter_status         text NOT NULL DEFAULT 'CONFIRMED'
        CHECK (encounter_status IN ('HOLDING','CONFIRMED','CHECKED_IN','IN_PROGRESS','COMPLETED','CANCELLED','NO_SHOW','EXPIRED')),
    queue_number         integer CHECK (queue_number > 0),
    estimated_exam_at    TIMESTAMPTZ,
    qr_code              text,
    hold_expires_at      TIMESTAMPTZ,
    checked_in_at        TIMESTAMPTZ,
    cancelled_by_id      INTEGER REFERENCES users(user_id),
    cancel_reason        text,
    cancel_origin        text CHECK (cancel_origin IN ('PATIENT','HOSPITAL')),
    cancelled_at         TIMESTAMPTZ,
    refund_reference_at  TIMESTAMPTZ,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT encounter_snapshot_pair CHECK ((consultation_fee_snapshot IS NULL) = (deposit_amount_snapshot IS NULL)),
    CONSTRAINT encounter_deposit_limit CHECK (deposit_amount_snapshot <= consultation_fee_snapshot),
    CONSTRAINT encounter_schedule_queue_unique UNIQUE (schedule_id, queue_number),
    CONSTRAINT encounter_hold_online_only CHECK (hold_expires_at IS NULL OR encounter_type = 'ONLINE'),
    CONSTRAINT encounter_holding_expiry CHECK (
        encounter_status <> 'HOLDING' OR (encounter_type = 'ONLINE' AND hold_expires_at IS NOT NULL)
    )
);

-- 10. ENCOUNTER_STATUS_LOG (Lịch sử trạng thái lượt khám)
CREATE TABLE IF NOT EXISTS encounter_status_log (
    log_id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    encounter_id         INTEGER NOT NULL REFERENCES encounter(encounter_id),
    old_status       text CHECK (old_status IN ('HOLDING','CONFIRMED','CHECKED_IN','IN_PROGRESS','COMPLETED','CANCELLED','NO_SHOW','EXPIRED')),
    new_status       text NOT NULL CHECK (new_status IN ('HOLDING','CONFIRMED','CHECKED_IN','IN_PROGRESS','COMPLETED','CANCELLED','NO_SHOW','EXPIRED')),
    changed_by_id    INTEGER NOT NULL REFERENCES users(user_id),
    note             text,
    changed_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 11. ENCOUNTER_TRANSFER_LOG (Lịch sử chuyển bác sĩ)
CREATE TABLE IF NOT EXISTS encounter_transfer_log (
    log_id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    encounter_id             INTEGER NOT NULL REFERENCES encounter(encounter_id),
    old_doctor_id        INTEGER NOT NULL REFERENCES doctor_profile(doctor_profile_id),
    new_doctor_id        INTEGER NOT NULL REFERENCES doctor_profile(doctor_profile_id),
    transferred_by_id    INTEGER NOT NULL REFERENCES users(user_id),
    reason               text,
    transferred_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT transfer_different_doctor CHECK (old_doctor_id <> new_doctor_id)
);

-- 12. PAYMENT (Thanh toán)
CREATE TABLE IF NOT EXISTS payment (
    payment_id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    encounter_id              INTEGER NOT NULL REFERENCES encounter(encounter_id),
    payment_type          text NOT NULL CHECK (payment_type IN ('DEPOSIT','EXAM_FEE','REFUND')),
    amount                BIGINT NOT NULL CHECK (amount >= 0),
    payment_method        text NOT NULL CHECK (payment_method IN ('CASH','BANK','EWALLET','CARD')),
    transaction_status    text NOT NULL DEFAULT 'PENDING'
        CHECK (transaction_status IN ('PENDING','SUCCESS','FAILED','REFUNDED')),
    transaction_code      text UNIQUE,
    original_payment_id   INTEGER REFERENCES payment(payment_id),
    created_by_id         INTEGER REFERENCES users(user_id),
    processed_by_id       INTEGER REFERENCES users(user_id),
    reason                text,
    failure_reason        text,
    result_received_at    TIMESTAMPTZ,
    paid_at               TIMESTAMPTZ,
    refunded_at           TIMESTAMPTZ,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 13. MEDICAL_RECORD (Hồ sơ khám bệnh)
CREATE TABLE IF NOT EXISTS medical_record (
    record_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    encounter_id        INTEGER NOT NULL UNIQUE REFERENCES encounter(encounter_id),
    diagnosis       text,
    treatment       text,
    doctor_notes    text,
    examined_at     TIMESTAMPTZ,
    version         INTEGER NOT NULL DEFAULT 0 CHECK (version >= 0),
    revision_history JSONB NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(revision_history)='array'),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 14. PRESCRIPTION_ITEM (Chi tiết đơn thuốc)
CREATE TABLE IF NOT EXISTS prescription_item (
    item_id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_id          INTEGER NOT NULL REFERENCES medical_record(record_id),
    medication_name    text NOT NULL CHECK (trim(medication_name) <> ''),
    dosage             text,
    quantity           integer NOT NULL CHECK (quantity > 0),
    instructions       text
);

-- 15. REVIEW (Đánh giá)
CREATE TABLE IF NOT EXISTS review (
    review_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_id     INTEGER NOT NULL UNIQUE REFERENCES medical_record(record_id),
    rating        integer NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment       text,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 16. NOTIFICATION (Thông báo)
CREATE TABLE IF NOT EXISTS notification (
    notification_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              INTEGER NOT NULL REFERENCES users(user_id),
    event_key            text,
    notification_type    text NOT NULL CHECK (trim(notification_type) <> ''),
    title                text NOT NULL CHECK (trim(title) <> ''),
    content              text NOT NULL,
    reference_type       text,
    reference_id         INTEGER,
    is_read              INTEGER NOT NULL DEFAULT 0 CHECK (is_read IN (0,1)),
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT notification_reference_pair CHECK (
        (reference_type IS NULL AND reference_id IS NULL) OR
        (reference_type IS NOT NULL AND trim(reference_type) <> '' AND reference_id IS NOT NULL)
    )
);

-- 17. ARTICLE (Bài viết)
CREATE TABLE IF NOT EXISTS article (
    article_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id        INTEGER NOT NULL REFERENCES users(user_id),
    title            text NOT NULL CHECK (trim(title) <> ''),
    slug             text NOT NULL UNIQUE CHECK (trim(slug) <> ''),
    category         text,
    thumbnail_url    text,
    content          text NOT NULL,
    is_active        INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
    published_at     TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 18. SYSTEM_CONFIGURATION (Cấu hình hệ thống)
CREATE TABLE IF NOT EXISTS system_configuration (
    config_key      text NOT NULL PRIMARY KEY CHECK (trim(config_key) <> ''),
    config_value    text NOT NULL,
    description     text,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 19. ROLE_REQUEST (Yêu cầu đổi vai trò)
CREATE TABLE IF NOT EXISTS role_request (
    request_id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              INTEGER NOT NULL REFERENCES users(user_id),
    requested_role_id    INTEGER NOT NULL REFERENCES role(role_id),
    reason               text CHECK (reason IS NULL OR trim(reason) <> ''),
    request_status       text NOT NULL DEFAULT 'PENDING'
        CHECK (request_status IN ('PENDING','APPROVED','REJECTED')),
    reviewed_by_id       INTEGER REFERENCES users(user_id),
    reviewed_at          TIMESTAMPTZ,
    review_note          text CHECK (review_note IS NULL OR trim(review_note) <> ''),
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT role_request_review CHECK (
        (request_status = 'PENDING' AND reviewed_by_id IS NULL AND reviewed_at IS NULL) OR
        (request_status IN ('APPROVED','REJECTED') AND reviewed_by_id IS NOT NULL AND reviewed_at IS NOT NULL)
    ),
    CONSTRAINT role_request_no_self_review CHECK (reviewed_by_id <> user_id),
    CONSTRAINT role_request_review_time CHECK (reviewed_at IS NULL OR reviewed_at >= created_at),
    CONSTRAINT role_request_rejection_note CHECK (request_status <> 'REJECTED' OR review_note IS NOT NULL)
);

-- 20. NURSE_ASSIGNMENT (Phân công điều dưỡng theo ca)
-- Phòng và chuyên khoa được xác định qua work_schedule, không lưu trùng ở đây.
CREATE TABLE IF NOT EXISTS nurse_assignment (
    assignment_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nurse_id         INTEGER NOT NULL REFERENCES users(user_id),
    schedule_id      INTEGER NOT NULL REFERENCES work_schedule(schedule_id),
    assigned_by_id   INTEGER NOT NULL REFERENCES users(user_id),
    assigned_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked_at       TIMESTAMPTZ,
    revoked_by_id    INTEGER REFERENCES users(user_id),
    note             text,
    CONSTRAINT nurse_assignment_revocation CHECK ((revoked_at IS NULL) = (revoked_by_id IS NULL)),
    CONSTRAINT nurse_assignment_revocation_time CHECK (revoked_at IS NULL OR revoked_at >= assigned_at)
);

-- Index: giữ nguyên UNIQUE có điều kiện để chống yêu cầu/phân công/hoàn tiền lặp.
CREATE UNIQUE INDEX IF NOT EXISTS idx_role_request_pending ON role_request(user_id)
WHERE request_status = 'PENDING';
CREATE INDEX IF NOT EXISTS idx_role_request_role ON role_request(requested_role_id);
CREATE INDEX IF NOT EXISTS idx_role_request_reviewer ON role_request(reviewed_by_id);
CREATE INDEX IF NOT EXISTS idx_role_request_status_created ON role_request(request_status, created_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_nurse_assignment_active ON nurse_assignment(nurse_id, schedule_id)
WHERE revoked_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_nurse_assignment_schedule ON nurse_assignment(schedule_id);
CREATE INDEX IF NOT EXISTS idx_nurse_assignment_assigner ON nurse_assignment(assigned_by_id);
CREATE INDEX IF NOT EXISTS idx_nurse_assignment_revoker ON nurse_assignment(revoked_by_id);

-- Index cho FK va cac truy van theo lich, benh nhan, lich su, thong bao.
-- UNIQUE/PRIMARY KEY da tu tao index, khong tao lai index trung lap.
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role_id);
CREATE INDEX IF NOT EXISTS idx_auth_token_lookup ON auth_token(token_hash, token_type);
CREATE INDEX IF NOT EXISTS idx_auth_token_user ON auth_token(user_id);
CREATE INDEX IF NOT EXISTS idx_auth_token_expiry ON auth_token(expires_at) WHERE used_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_patient_user ON patient(user_id);
CREATE INDEX IF NOT EXISTS idx_doctor_department ON doctor_profile(department_id);
CREATE INDEX IF NOT EXISTS idx_room_department ON room(department_id);
CREATE INDEX IF NOT EXISTS idx_schedule_date_status ON work_schedule(work_date, schedule_status);
CREATE INDEX IF NOT EXISTS idx_encounter_patient_created ON encounter(patient_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_encounter_doctor ON encounter(doctor_profile_id);
CREATE INDEX IF NOT EXISTS idx_encounter_room ON encounter(room_id);
CREATE INDEX IF NOT EXISTS idx_encounter_creator ON encounter(created_by_id);
CREATE INDEX IF NOT EXISTS idx_encounter_canceller ON encounter(cancelled_by_id);
CREATE INDEX IF NOT EXISTS idx_encounter_expiring ON encounter(hold_expires_at) WHERE encounter_status = 'HOLDING';
CREATE INDEX IF NOT EXISTS idx_encounter_status_history ON encounter_status_log(encounter_id, changed_at);
CREATE INDEX IF NOT EXISTS idx_encounter_status_actor ON encounter_status_log(changed_by_id);
CREATE INDEX IF NOT EXISTS idx_transfer_history ON encounter_transfer_log(encounter_id, transferred_at);
CREATE INDEX IF NOT EXISTS idx_transfer_old_doctor ON encounter_transfer_log(old_doctor_id);
CREATE INDEX IF NOT EXISTS idx_transfer_new_doctor ON encounter_transfer_log(new_doctor_id);
CREATE INDEX IF NOT EXISTS idx_transfer_actor ON encounter_transfer_log(transferred_by_id);
CREATE INDEX IF NOT EXISTS idx_payment_encounter ON payment(encounter_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_payment_refund_original ON payment(original_payment_id)
    WHERE payment_type='REFUND' AND original_payment_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_prescription_record ON prescription_item(record_id);
CREATE INDEX IF NOT EXISTS idx_notification_user_created ON notification(user_id, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS idx_notification_user_event ON notification(user_id,event_key);
CREATE INDEX IF NOT EXISTS idx_article_author ON article(author_id);



-- Cấu hình mặc định cho database mới; khởi động lại cùng schema không ghi đè giá trị đã lưu.
INSERT INTO system_configuration(config_key,config_value,description) VALUES
('APPOINTMENT_HOLD_MINUTES','10','Giữ chỗ online 10 phút; chính sách đã chốt'),
('DEFAULT_DEPOSIT_PERCENT','100','Cọc 100% giá bác sĩ cho lượt đặt mới'),
('NO_SHOW_FORFEIT_DEPOSIT','true','No-show mất cọc'),
('CHECKIN_EARLY_MINUTES','30','Online check-in ít nhất 30 phút trước giờ hẹn'),
('CHECKIN_LATE_MINUTES','0','Không check-in sau hạn đã chốt'),
('NO_SHOW_GRACE_MINUTES','15','No-show sau kết thúc ca 15 phút'),
('CANCEL_HOURS_LIMIT','12','Hủy từ 12 giờ trước giờ hẹn được hoàn 50% cọc'),
('CANCEL_REFUND_PERCENT','50','Bệnh nhân hủy đúng hạn hoàn 50%; lỗi bệnh viện hoàn toàn bộ'),
('MAX_REVIEW_RATING','5','Điểm đánh giá từ 1 đến 5'),
('REMINDER_BEFORE_HOURS','24','Nhắc lịch trong khoảng bao nhiêu giờ trước hẹn'),
('HOSPITAL_NAME','Medicare Demo Clinic','Tên cơ sở khám bệnh'),
('SUPPORT_PHONE','19001234','Số hỗ trợ'),
('ALLOW_WALK_IN','true','Cho phép tiếp nhận walk-in mới')
ON CONFLICT (config_key) DO NOTHING;

-- Trigger tự cập nhật updated_at.
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at = clock_timestamp();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trg_users_updated_at BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE OR REPLACE TRIGGER trg_patient_updated_at BEFORE UPDATE ON patient
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE OR REPLACE TRIGGER trg_department_updated_at BEFORE UPDATE ON department
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE OR REPLACE TRIGGER trg_doctor_profile_updated_at BEFORE UPDATE ON doctor_profile
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE OR REPLACE TRIGGER trg_room_updated_at BEFORE UPDATE ON room
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE OR REPLACE TRIGGER trg_work_schedule_updated_at BEFORE UPDATE ON work_schedule
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE OR REPLACE TRIGGER trg_encounter_updated_at BEFORE UPDATE ON encounter
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE OR REPLACE TRIGGER trg_payment_updated_at BEFORE UPDATE ON payment
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE OR REPLACE TRIGGER trg_medical_record_updated_at BEFORE UPDATE ON medical_record
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE OR REPLACE TRIGGER trg_review_updated_at BEFORE UPDATE ON review
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE OR REPLACE TRIGGER trg_article_updated_at BEFORE UPDATE ON article
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE OR REPLACE TRIGGER trg_system_configuration_updated_at BEFORE UPDATE ON system_configuration
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE OR REPLACE TRIGGER trg_role_request_updated_at BEFORE UPDATE ON role_request
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
