-- Nâng cấp database đã chạy bản 18 bảng. Không xóa hoặc đoán giá dữ liệu cũ.
-- Chạy trước khi build lại backend. Có thể chạy lại an toàn.
BEGIN;
SELECT pg_advisory_xact_lock(78124001);
ALTER TABLE patient ADD COLUMN IF NOT EXISTS archived_at TIMESTAMPTZ;
ALTER TABLE visit ADD COLUMN IF NOT EXISTS consultation_fee_snapshot BIGINT CHECK (consultation_fee_snapshot >= 0);
ALTER TABLE visit ADD COLUMN IF NOT EXISTS deposit_amount_snapshot BIGINT CHECK (deposit_amount_snapshot >= 0);
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'visit'::regclass AND conname = 'visit_snapshot_pair') THEN
        ALTER TABLE visit ADD CONSTRAINT visit_snapshot_pair CHECK ((consultation_fee_snapshot IS NULL) = (deposit_amount_snapshot IS NULL));
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'visit'::regclass AND conname = 'visit_deposit_limit') THEN
        ALTER TABLE visit ADD CONSTRAINT visit_deposit_limit CHECK (deposit_amount_snapshot <= consultation_fee_snapshot);
    END IF;
END;
$$;
-- 19. ROLE_REQUEST (Yêu cầu đổi vai trò)
CREATE TABLE IF NOT EXISTS role_request (
    request_id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              INTEGER NOT NULL REFERENCES users(user_id),
    requested_role_id    INTEGER NOT NULL REFERENCES role(role_id),
    reason               text CHECK (reason IS NULL OR trim(reason) <> ''),
    request_status       text NOT NULL DEFAULT 'PENDING'
        CHECK (request_status IN ('PENDING','APPROVED','REJECTED')),
    reviewed_by_id       INTEGER REFERENCES users(user_id),
    reviewed_at          TIMESTAMPTZ,
    review_note          text CHECK (review_note IS NULL OR trim(review_note) <> ''),
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT role_request_review CHECK (
        (request_status = 'PENDING' AND reviewed_by_id IS NULL AND reviewed_at IS NULL) OR
        (request_status IN ('APPROVED','REJECTED') AND reviewed_by_id IS NOT NULL AND reviewed_at IS NOT NULL)
    ),
    CONSTRAINT role_request_no_self_review CHECK (reviewed_by_id <> user_id),
    CONSTRAINT role_request_review_time CHECK (reviewed_at IS NULL OR reviewed_at >= created_at),
    CONSTRAINT role_request_rejection_note CHECK (request_status <> 'REJECTED' OR review_note IS NOT NULL)
);

-- 20. NURSE_ASSIGNMENT (Phân công điều dưỡng theo ca)
-- Phòng và chuyên khoa được xác định qua work_schedule, không lưu trùng ở đây.
CREATE TABLE IF NOT EXISTS nurse_assignment (
    assignment_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nurse_id         INTEGER NOT NULL REFERENCES users(user_id),
    schedule_id      INTEGER NOT NULL REFERENCES work_schedule(schedule_id),
    assigned_by_id   INTEGER NOT NULL REFERENCES users(user_id),
    assigned_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked_at       TIMESTAMPTZ,
    revoked_by_id    INTEGER REFERENCES users(user_id),
    note             text,
    CONSTRAINT nurse_assignment_revocation CHECK ((revoked_at IS NULL) = (revoked_by_id IS NULL)),
    CONSTRAINT nurse_assignment_revocation_time CHECK (revoked_at IS NULL OR revoked_at >= assigned_at)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_role_request_pending ON role_request(user_id)
WHERE request_status = 'PENDING';
CREATE INDEX IF NOT EXISTS idx_role_request_role ON role_request(requested_role_id);
CREATE INDEX IF NOT EXISTS idx_role_request_reviewer ON role_request(reviewed_by_id);
CREATE INDEX IF NOT EXISTS idx_role_request_status_created ON role_request(request_status, created_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_nurse_assignment_active ON nurse_assignment(nurse_id, schedule_id)
WHERE revoked_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_nurse_assignment_schedule ON nurse_assignment(schedule_id);
CREATE INDEX IF NOT EXISTS idx_nurse_assignment_assigner ON nurse_assignment(assigned_by_id);
CREATE INDEX IF NOT EXISTS idx_nurse_assignment_revoker ON nurse_assignment(revoked_by_id);

CREATE OR REPLACE TRIGGER trg_role_request_updated_at BEFORE UPDATE ON role_request
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
COMMIT;
