"""Hằng số dùng chung của backend."""

ROLE_USER = 'USER'
ROLE_DOCTOR = 'DOCTOR'
ROLE_RECEPTIONIST = 'RECEPTIONIST'
ROLE_NURSE = 'NURSE'
ROLE_ADMIN = 'ADMIN'
ALL_ROLES = (ROLE_USER, ROLE_DOCTOR, ROLE_RECEPTIONIST, ROLE_NURSE, ROLE_ADMIN)

ACCOUNT_ACTIVE = 'ACTIVE'
ACCOUNT_LOCKED = 'LOCKED'
ACCOUNT_STATUSES = (ACCOUNT_ACTIVE, ACCOUNT_LOCKED)

APPROVAL_PENDING = 'PENDING'
APPROVAL_APPROVED = 'APPROVED'
APPROVAL_REJECTED = 'REJECTED'
APPROVAL_STATUSES = (APPROVAL_PENDING, APPROVAL_APPROVED, APPROVAL_REJECTED)

TOKEN_RESET_PASSWORD = 'RESET_PASSWORD'
TOKEN_VERIFY_EMAIL = 'VERIFY_EMAIL'
TOKEN_OTP = 'OTP'

ACCESS_TOKEN_TTL_SECONDS = 2 * 60 * 60
OTP_TTL_MINUTES = 10
RESET_TOKEN_TTL_MINUTES = 10
EMAIL_VERIFY_TTL_MINUTES = 24 * 60

MIN_PASSWORD_LENGTH = 8
MAX_PASSWORD_LENGTH = 128

DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100
